
                                                <div class="d-flex justify-content-center gap-1">
                                                    @if (isset($orders->items[0]))
                                                        <button type="button" class="btn-utility"
                                                            onclick="assign_salesperson('{{ $orders->order_id }}', '{{ $orders->items[0]->salesperson_id }}'); event.preventDefault();"
                                                            data-bs-toggle="tooltip" data-bs-placement="top"
                                                            title="Assign Salesperson">

                                                            <i
                                                                class="fas fa-user-tie {{ !empty($orders->items[0]->salesperson_id) ? 'text-success' : '' }}"></i>
                                                        </button>
                                                    @else
                                                        -
                                                    @endif


                                                    @if (Route::currentRouteName() == 'cleaning_package_order' ||
                                                            Route::currentRouteName() == 'handyman-service-order' ||
                                                            Route::currentRouteName() == 'salon-spa-order' ||
                                                            Route::currentRouteName() == 'pest-control-order')
                                                        {{-- ================= SALES PERSON ================= --}}



                                                        @if (isset($orders->items[0]))
                                                            {{-- If Cleaner ID = 2 → Assign Single Crew --}}
                                                            @if ($orders->items[0]->cleaner_id == 2)
                                                                <button type="button" class="btn-utility"
                                                                    onclick="assign_cleaner('{{ $orders->order_id }}', '{{ $orders->items[0]->service_id }}', '{{ $orders->items[0]->subservice_id }}', '{{ $orders->items[0]->cleaner_id }}'); event.preventDefault();">
                                                                    <i
                                                                        class="fas fa-user {{ !empty($orders->items[0]->cleaner_id) ? 'text-success' : '' }}"></i>
                                                                </button>

                                                                {{-- If Cleaner Already Assigned or Not Assigned --}}
                                                            @else
                                                                <button type="button" class="btn-utility"
                                                                    onclick="assign_multi_cleaner(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{{ $orders->order_id }}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{{ $orders->items[0]->service_id }}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{{ $orders->items[0]->subservice_id }}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{{ $orders->items[0]->how_many_cleaners_do_you_need }}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{{ $orders->items[0]->cleaner_id }}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ); event.preventDefault();"
                                                                    title="Assign Multiple Crew">

                                                                    <i
                                                                        class="fas fa-users {{ !empty($orders->items[0]->cleaner_id) ? 'text-success' : '' }}"></i>
                                                                </button>
                                                            @endif
                                                        @else
                                                            {{ '-' }}
                                                        @endif

                                                        {{-- @if (isset($orders->items[0]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @if (!empty($orders->items[0]->cleaner_id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ url('mark-attendance/' . $orders->order_id) }}" class="btn-utility"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data-bs-toggle="tooltip" title="Attendance">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-calendar-check"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endif --}}

                                                        {{-- ================= ADD PER CREW PRICE ================= --}}
                                                        {{-- @if ($orders->items[0]->subservice_id != 28) --}}
                                                        {{-- @if (!empty($orders->items[0]->cleaner_id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @if (empty($orders->items[0]->cleaner_price) && $orders->items[0]->cleaner_price == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="button" class="btn-utility"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onclick="add_cleaner_price('{{ $orders->order_id }}');" data-bs-toggle="tooltip"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data-bs-placement="top" title="Add Per Crew Price">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-dollar-sign"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endif --}}
                                                        {{-- @endif --}}
                                                    @endif

                                                    @if ($orders->payment_status == 'Success' || $orders->payment_status == 'paid')
                                                        @if ($orders->items[0]->service_id == 50)
                                                            <button type="button" class="btn-utility"
                                                                onclick="assign_vendor_car('{{ $orders->order_id }}', '{{ $orders->vendor_id }}'); event.preventDefault();"
                                                                data-bs-toggle="tooltip" data-bs-placement="top"
                                                                title="Assign Vendor car">

                                                                <i
                                                                    class="fas fa-user {{ !empty($orders->vendor_id) ? 'text-success' : '' }}"></i>
                                                            </button>
                                                        @else
                                                            <button type="button" class="btn-utility"
                                                                onclick="assign_vendor('{{ $orders->order_id }}', '{{ $orders->vendor_id }}'); event.preventDefault();"
                                                                data-bs-toggle="tooltip" data-bs-placement="top"
                                                                title="Assign Vendor">

                                                                <i
                                                                    class="fas fa-user {{ !empty($orders->vendor_id) ? 'text-success' : '' }}"></i>
                                                            </button>
                                                        @endif
                                                    @endif

                                                    <button type="button" class="btn-utility"
                                                        onclick="openLocationLink('{{ $orders->order_id }}', '{{ $orders->items[0]->location_link }}'); event.preventDefault();"
                                                        title="Location Link">

                                                        <i
                                                            class="fas fa-map-marker-alt {{ !empty($orders->items[0]->location_link) ? 'text-success' : '' }}"></i>
                                                    </button>

                                                </div>
